export const GET_NAVS_CATEGORIES = 'GET_NAVS_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY_DETAIL = 'GET_CATEGORY_DETAIL';
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const GET_CARSOUL_TOPICS = 'GET_CARSOUL_TOPICS';
export const GET_RECENT_TOPICS = 'GET_RECENT_TOPICS';
export const GET_ALL_TOPICS = 'GET_ALL_TOPICS';
export const GET_CATEGORY_TOPICS = 'GET_CATEGORY_TOPICS';
export const GET_ADMIN_TOPICS = 'GET_ADMIN_TOPICS';

export const VIEW_TOPIC_DETAIL = 'VIEW_TOPIC_DETAIL';
export const ADD_NEW_TOPIC = 'ADD_NEW_TOPIC';
export const UPDATE_TOPIC = 'UPDATE_TOPIC';
export const RESET_UPDATE_TOPIC = 'RESET_UPDATE_TOPIC';
export const RESET_ADD_TOPIC = 'RESET_ADD_TOPIC';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const SET_UPLOADED_PCT = 'SET_UPLOADED_PCT';
export const DELETE_FILE = 'DELETE_FILE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER = 'SET_USER';
export const GET_USERS = 'GET_USERS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'UPDATE_USER';

export const GET_DASHBOARD_COUNTS = 'GET_DASHBOARD_COUNTS';

export const ADD_COMMENT = 'ADD_COMMENT';
export const RESET_ADD_COMMENT = 'RESET_ADD_COMMENT';
export const GET_TOPICS_COMMENTS = 'GET_TOPICS_COMMENTS';
export const GET_COMMENTS_ADMIN = 'GET_COMMENTS_ADMIN';
export const PUBLISH_COMMENT = 'PUBLISH_COMMENT';
export const RESET_PUBLISH_COMMENT = 'RESET_PUBLISH_COMMENT';

export const SEARCH_QUERY = 'SEARCH_QUERY';

export const ADD_ALBUM = 'ADD_ALBUM';
export const GET_ALBUMS = 'GET_ALBUMS';
export const GET_MEDIAS = 'GET_MEDIAS';
export const ADD_NEW_MEDIA = 'ADD_NEW_MEDIA';
export const DOWNLOAD_SONG = 'DOWNLOAD_SONG';
export const EDIT_SONG = 'EDIT_SONG';
export const DELETE_SONG = 'DELETE_SONG';
export const SHARE_SONG = 'SHARE_SONG';
export const SET_FILE_PATH = 'SET_FILE_PATH';
export const RESET_FILE_PATH = 'RESET_FILE_PATH';
export const GET_MEDIA_COUNTS = 'GET_MEDIA_COUNTS';

export const ADD_COMMUNIQUE = 'ADD_COMMUNIQUE';
export const GET_COMMUNIQUES = 'GET_COMMUNIQUES';
export const GET_PUBLISHED_COMMUNIQUE = 'GET_PUBLISHED_COMMUNIQUE';
export const PUBLISH_COMMUNIQUE = 'PUBLISH_COMMUNIQUE';

export const SEND_CONTACT_US = 'SEND_CONTACT_US';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
