export const GET_NAVS_CATEGORIES = 'GET_NAVS_CATEGORIES';
export const SET_LANGUAGE = 'SET_LANGUAGE';

export const GET_CARSOUL_TOPICS = 'GET_CARSOUL_TOPICS';
export const GET_RECENT_TOPICS = 'GET_RECENT_TOPICS';
export const GET_ALL_TOPICS = 'GET_ALL_TOPICS';
export const GET_CATEGORY_TOPICS = 'GET_CATEGORY_TOPICS';
