export const GET_NAVS_CATEGORIES = 'GET_NAVS_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const GET_CARSOUL_TOPICS = 'GET_CARSOUL_TOPICS';
export const GET_RECENT_TOPICS = 'GET_RECENT_TOPICS';
export const GET_ALL_TOPICS = 'GET_ALL_TOPICS';
export const GET_CATEGORY_TOPICS = 'GET_CATEGORY_TOPICS';

export const VIEW_TOPIC_DETAIL = 'VIEW_TOPIC_DETAIL';
export const ADD_NEW_TOPIC = 'ADD_NEW_TOPIC';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const SET_UPLOADED_PCT = 'SET_UPLOADED_PCT';

export const LOGIN_USER = 'LOGIN_USER';
export const SET_USER = 'SET_USER';
